INSERT INTO  CP2020Db.SKILLS (skillName, skillType) VALUES 
("Charimatic Leadership", "Special"),
("Combat Sense", "Special"),
("Credibility", "Special"),
("Family", "Special"),
("Jury rig", "Special"),
("Medical tech", "Special"),
("Negotiate", "Special"),
("Debate", "Special"),
("Personal Grooming", "Attract"),
("Wardrobe", "Attract"),
("Endurance", "Body"),
("Strength Feat", "Body"),
("Swimming", "Body"),
("Interrogation", "Cool"),
("Intimidate", "Cool"),
("Oratory", "Cool"),
("Resist Torture/Drugs", "Cool"),
("Streewise", "Cool"),
("Human Perception", "Empathy"),
("Interview", "Empathy"),
("Leadership", "Empathy"),
("Seduction", "Empathy"),
("Social", "Empathy"),
("Persuasion", "Empathy"),
("Perform", "Empathy")
("Accounting", "Intelligence"),
("Anthropology", "Intelligence"),
("Awareness", "Intelligence"),
("Biology", "Intelligence"),
("Botany", "Intelligence"),
("Chemistry", "Intelligence"),
("Composition", "Intelligence"),
("Diagnose Illness", "Intelligence"),
("Education & Gen. Know.", "Intelligence"),
("Gamble", "Intelligence"),
("Geology", "Intelligence"),
("History", "Intelligence"),
("Research", "Intelligence"),
("Mathematics", "Intelligence"),
("Physics", "Intelligence"),
("Programming", "Intelligence"),
("Shadow/track", "Intelligence"),
("System Knowledge", "Intelligence"),
("Teaching", "Intelligence"),
("Trade Stocks", "Intelligence"),
("Wilderness Survival", "Intelligence"),
("Zoology", "Intelligence"),
("Archery", "Reflex"),
("Athletics", "Reflex"),
("Brawling", "Reflex"),
("Dance", "Reflex"),
("Dodge & Escape"),
("Driving", "Reflex"),
("Fencing", "Reflex"),
("Handgun", "Reflex"),
("Heavy Weapons", "Reflex"),
("Melee", "Reflex"),
("Motorcycle", "Reflex"),
("Operate Hvy. Machinery", "Reflex"),
("Pilot(Gyro)", "Reflex"),
("Pilot(Fixed Wing)", "Reflex"),
("Pilot(Dirigible)", "Reflex"),
("Pilot(VTOL)", "Reflex"),
("Rifle", "Reflex"),
("Stealth", "Reflex"),
("Submachinegun(SMG)", "Reflex"),
("Aero Tech", "Tech"),
("AV Tech", "Tech"),
("Basic Tech", "Tech"),
("Cryotank Op;